//Code to pull OSC API list from Figure 53 website:
// var cs = []; ps = document.getElementsByTagName('h4'); for (var i=0, len = ps.length; i<len; i++) {cs.push(ps[i].textContent);} JSON.stringify(cs).replace(/,/g, ',\n').replace(/\/workspace\/{id}\//g,'/');
//Website is: https://qlab.app/docs/v4/scripting/osc-dictionary-v4/
export const qlabCommandList = [
  '/alwaysReply {number}',
  '/auditionWindow {number}',
  '/toggleAuditionWindow',
  '/fontNames',
  '/fontFamiliesAndStyles',
  '/liveFadePreview {number}',
  '/toggleLiveFadePreview',
  '/overrides/artNetEnabled {number}',
  '/overrides/toggleArtNet',
  '/overrides/midiInputEnabled {number}',
  '/overrides/toggleMidiInput',
  '/overrides/midiOutputEnabled {number}',
  '/overrides/toggleMidiOutput',
  '/overrides/mscInputEnabled {number}',
  '/overrides/toggleMscInput',
  '/overrides/mscOutputEnabled {number}',
  '/overrides/toggleMscOutput',
  '/overrides/sysexInputEnabled {number}',
  '/overrides/toggleSysexInput',
  '/overrides/sysexOutputEnabled {number}',
  '/overrides/toggleSysexOutput',
  '/overrides/oscInputEnabled {number}',
  '/overrides/toggleOscInput',
  '/overrides/oscOutputEnabled {number}',
  '/overrides/toggleOscOutput',
  '/overrides/timecodeInputEnabled {number}',
  '/overrides/toggleTimecodeInput',
  '/overrides/timecodeOutputEnabled {number}',
  '/overrides/toggleTimecodeOutput',
  '/overrideWindow {number}',
  '/toggleOverrideWindow',
  '/replyFormat {format_string}',
  '/timecodeWindow {number}',
  '/toggleTimecodeWindow',
  '/version',
  '/workingDirectory {path}',
  '/workspaces',
  '/basePath',
  '/connect {passcode_string}',
  '/disconnect',
  '/doubleGoWindowRemaining',
  '/cueLists',
  '/selectedCues',
  '/runningCues',
  '/runningOrPausedCues',
  '/cueLists/shallow',
  '/selectedCues/shallow',
  '/runningCues/shallow',
  '/runningOrPausedCues/shallow',
  '/cueLists/uniqueIDs',
  '/selectedCues/uniqueIDs',
  '/runningCues/uniqueIDs',
  '/runningOrPausedCues/uniqueIDs',
  '/cueLists/uniqueIDs/shallow',
  '/selectedCues/uniqueIDs/shallow',
  '/runningCues/uniqueIDs/shallow',
  '/runningOrPausedCues/uniqueIDs/shallow',
  '/dashboard/clear',
  '/dashboard/updateLatestCue',
  '/dashboard/updateOriginatingCues',
  '/dashboard/updateSelectedCues',
  '/dashboard/newCueWithAll',
  '/dashboard/newCueWithChanges',
  '/dashboard/recordAllToLatest',
  '/dashboard/recordAllToSelected',
  '/dashboard/revert',
  '/dashboard/redo',
  '/dashboard/mode {string}',
  '/dashboard/nextMode',
  '/dashboard/setLight {string} {setting} {time}',
  '/dashboard/undo',
  '/delete/{cue_number}',
  '/delete_id/{cue_id}',
  '/delete/active',
  '/delete/selected',
  '/fullScreen {number}',
  '/toggleFullScreen',
  '/go {cue_number}',
  '/go/{cue_number}',
  '/lightDashboard {number}',
  '/toggleLightDashboard',
  '/move/{cue_id} {new_index} {new_parent_cue_id}',
  '/new {cue_type}',
  '/panic',
  '/panicInTime {number}',
  '/pause',
  '/playhead/{cue_number}',
  '/playheadId/{cue_id}',
  '/playbackPosition/{cue_number}',
  '/playbackPositionId/{cue_id}',
  '/playhead/next',
  '/playbackPosition/next',
  '/playhead/previous',
  '/playbackPosition/previous',
  '/playhead/nextSequence',
  '/playbackPosition/nextSequence',
  '/playhead/previousSequence',
  '/playbackPosition/previousSequence',
  '/renumber {startNumber} {incrementNumber}',
  '/reset',
  '/resume',
  '/save',
  '/select/{cue_number}',
  '/select_id/{id}',
  '/select/next',
  '/select/previous',
  '/selectionIsPlayhead {number}',
  '/toggleSelectionIsPlayhead',
  '/showMode {number}',
  '/toggleEditShowMode',
  '/stop',
  '/hardStop',
  '/thump',
  '/undo',
  '/redo',
  '/updates {number}',
  '/settings/audio/maxVolume',
  '/settings/audio/minVolume',
  '/settings/audio/outputChannelNames',
  '/settings/mic/outputChannelNames',
  '/settings/general/minGoTime {number}',
  '/settings/video/surfaces',
  '/settings/video/surfaces/{surfaceID}',
  '/settings/video/surfaces/{surfaceID}/{screenIndex}/enableGrid {number}',
  '/settings/video/surfaces/{surfaceID}/{screenIndex}/enableGuides {number}',
  '/settings/video/surfaces/{surfaceID}/{screenIndex}/origin {location}',
  '/settings/video/surfaces/{surfaceID}/{screenIndex}/controlPoint {row_index} {column_index} {location}',
  '/settings/video/surfaces/{surfaceID}/{screenIndex}/resetControlPoints',
  '/cue/{cue_number}/actionElapsed',
  '/cue/{cue_number}/percentActionElapsed',
  '/cue/{cue_number}/allowsEditingDuration',
  '/cue/{cue_number}/armed {number}',
  '/cue/{cue_number}/autoLoad {number}',
  '/cue/{cue_number}/cartPosition',
  '/cue/{number}/children/shallow',
  '/cue/{number}/children/uniqueIDs',
  '/cue/{number}/children/uniqueIDs/shallow',
  '/cue/{cue_number}/colorName {string}',
  '/cue/{cue_number}/continueMode {number}',
  '/cue/{cue_number}/cueTargetId {string}',
  '/cue/{cue_number}/cueTargetNumber {string}',
  '/cue/{cue_number}/currentCueTarget',
  '/cue/{cue_number}/go',
  '/cue/{cue_number}/tempCueTargetNumber {string}',
  '/cue/{cue_number}/tempCueTargetId',
  '/cue/{cue_number}/currentDuration',
  '/cue/{cue_number}/tempDuration {number}',
  '/cue/{cue_number}/currentFileTime',
  '/cue/{cue_number}/defaultName',
  '/cue/{cue_number}/displayName',
  '/cue/{cue_number}/listName',
  '/cue/{cue_number}/duckLevel {number}',
  '/cue/{cue_number}/duckOthers {number}',
  '/cue/{cue_number}/duckTime {number}',
  '/cue/{cue_number}/duration {number}',
  '/cue/{cue_number}/fadeAndStopOthers {number}',
  '/cue/{cue_number}/fadeAndStopOthersTime {number}',
  '/cue/{cue_number}/fileTarget {string}',
  '/cue/{cue_number}/flagged {number}',
  '/cue/{cue_number}/hasCueTargets',
  '/cue/{cue_number}/hasFileTargets',
  '/cue/{cue_number}/isActionRunning',
  '/cue/{cue_number}/isBroken',
  '/cue/{cue_number}/isLoaded',
  '/cue/{cue_number}/isOverridden',
  '/cue/{cue_number}/isPanicking',
  '/cue/{cue_number}/isPaused',
  '/cue/{cue_number}/isRunning',
  '/cue/{cue_number}/isTailingOut',
  '/cue/{cue_number}/load',
  '/cue/{cue_number}/loadAt {number}',
  '/cue/{cue_number}/loadActionAt {number}',
  '/cue/{cue_number}/loadAndSetPlayhead',
  '/cue/{cue_number}/maxTimeInCueSequence',
  '/cue/{cue_number}/name {string}',
  '/cue/{cue_number}/notes {string}',
  '/cue/{cue_number}/number {string}',
  '/cue/{cue_number}/panic',
  '/cue/{cue_number}/panicInTime {number}',
  '/cue/{cue_number}/pause',
  '/cue/{cue_number}/hardPause',
  '/cue/{cue_number}/togglePause',
  '/cue/{cue_number}/parent',
  '/cue/{cue_number}/preview',
  '/cue/{cue_number}/preWait {number}',
  '/cue/{cue_number}/preWaitElapsed',
  '/cue/{cue_number}/percentPreWaitElapsed',
  '/cue/{cue_number}/postWait {number}',
  '/cue/{cue_number}/postWaitElapsed',
  '/cue/{cue_number}/percentPostWaitElapsed',
  '/cue/{cue_number}/resume',
  '/cue/{cue_number}/reset',
  '/cue/{cue_number}/secondTriggerAction {number}',
  '/cue/{cue_number}/secondTriggerOnRelease {number}',
  '/cue/{cue_number}/soloCueInTime {number}',
  '/cue/{cue_number}/start',
  '/cue/{cue_number}/startAndAutoloadNext',
  '/cue/{cue_number}/stop',
  '/cue/{cue_number}/hardStop',
  '/cue/{cue_number}/type',
  '/cue/{cue_number}/uniqueID',
  '/cue/{cue_number}/valuesForKeys {json_string}',
  '/cue/{cue_number}/valuesForKeysWithArguments {json_string}',
  '/cue/{cue_number}/cartColumns',
  '/cue/{cue_number}/cartRows',
  '/cue/{cue_number}/children',
  '/cue/{cue_number}/go',
  '/cue/{cue_number}/mode {number}',
  '/cue/{cue_number}/moveCartCue/{child} {row} {column}',
  '/cue/{cue_number}/playhead {string}',
  '/cue/{cue_number}/playbackPosition {string}',
  '/cue/{cue_number}/playheadId {string}',
  '/cue/{cue_number}/playbackPositionId {string}',
  '/cue/{cue_number}/doFade {number}',
  '/cue/{cue_number}/doPitchShift {number}',
  '/cue/{cue_number}/endTime {number}',
  '/cue/{cue_number}/gang {inChannel} {outChannel} {gang}',
  '/cue/{cue_number}/gang/{inChannel}/{outChannel} {gang}',
  '/cue/{cue_number}/infiniteLoop {number}',
  '/cue/{cue_number}/level {inChannel} {outChannel} {decibel}',
  '/cue/{cue_number}/level/{inChannel}/{outChannel} {decibel}',
  '/cue/{cue_number}/levels',
  '/cue/{cue_number}/liveAverageLevel/{outputChannel} {low} {high}',
  '/cue/{cue_number}/lockFadeToCue {number}',
  '/cue/{cue_number}/numChannelsIn',
  '/cue/{cue_number}/patch {number}',
  '/cue/{cue_number}/patchList',
  '/cue/{cue_number}/playCount {number}',
  '/cue/{cue_number}/rate {number}',
  '/cue/{cue_number}/liveRate {number}',
  '/cue/{cue_number}/setDefaultLevels',
  '/cue/{cue_number}/setSilentLevels',
  '/cue/{cue_number}/sliceMarkers',
  '/cue/{cue_number}/sliceMarker {index}',
  '/cue/{cue_number}/sliceMarker/{index}',
  '/cue/{cue_number}/sliceMarker/{index}/time',
  '/cue/{cue_number}/sliceMarker/{index}/playCount',
  '/cue/{cue_number}/addSliceMarker {time} {play_count}',
  '/cue/{cue_number}/deleteSliceMarker {index}',
  '/cue/{cue_number}/deleteSliceMarker/{index}',
  '/cue/{cue_number}/deleteSliceMarkers',
  '/cue/{cue_number}/sliceMarker {index} {time} {play_count}',
  '/cue/{cue_number}/sliceMarker/{index} {time} {play_count}',
  '/cue/{cue_number}/sliceMarker/{index}/time {time}',
  '/cue/{cue_number}/sliceMarker/{index}/time/+ {delta}',
  '/cue/{cue_number}/sliceMarker/{index}/time/- {delta}',
  '/cue/{cue_number}/sliceMarkers/time/+ {delta}',
  '/cue/{cue_number}/sliceMarkers/time/- {delta}',
  '/cue/{cue_number}/sliceMarker/{index}/playCount {play_count}',
  '/cue/{cue_number}/sliceMarker/{index}/playCount/+ {delta}',
  '/cue/{cue_number}/sliceMarker/{index}/playCount/- {delta}',
  '/cue/{cue_number}/lastSlicePlayCount {play_count}',
  '/cue/{cue_number}/lastSliceInfiniteLoop {number}',
  '/cue/{cue_number}/sliderLevel {channel} {decibel}',
  '/cue/{cue_number}/sliderLevel/{channel} {decibel}',
  '/cue/{cue_number}/sliderLevels',
  '/cue/{cue_number}/startTime {number}',
  '/cue/{cue_number}/channelOffset',
  '/cue/{cue_number}/channels {number}',
  '/cue/{cue_number}/setDefaultLevels',
  '/cue/{cue_number}/setSilentLevels',
  '/cue/{cue_number}/cueSize',
  '/cue/{cue_number}/doFade {number}',
  '/cue/{cue_number}/doPitchShift {number}',
  '/cue/{cue_number}/doEffect {number}',
  '/cue/{cue_number}/effectIndex {number}',
  '/cue/{cue_number}/effectSet {parameter} {value}',
  '/cue/{cue_number}/liveEffectSet {parameter} {value}',
  '/cue/{cue_number}/endTime {number}',
  '/cue/{cue_number}/fullScreen {number}',
  '/cue/{cue_number}/fullSurface {number}',
  '/cue/{cue_number}/gang {inChannel} {outChannel} {gang}',
  '/cue/{cue_number}/gang/{inChannel}/{outChannel} {gang}',
  '/cue/{cue_number}/holdLastFrame {number}',
  '/cue/{cue_number}/infiniteLoop {number}',
  '/cue/{cue_number}/layer {number}',
  '/cue/{cue_number}/level {inChannel} {outChannel} {decibel}',
  '/cue/{cue_number}/level/{inChannel}/{outChannel} {decibel}',
  '/cue/{cue_number}/levels',
  '/cue/{cue_number}/liveAverageLevel/{outputChannel} {low} {high}',
  '/cue/{cue_number}/lockFadeToCue {number}',
  '/cue/{cue_number}/numChannelsIn',
  '/cue/{cue_number}/opacity {number}',
  '/cue/{cue_number}/originX {number}',
  '/cue/{cue_number}/originY {number}',
  '/cue/{cue_number}/origin {x} {y}',
  '/cue/{cue_number}/patch {number}',
  '/cue/{cue_number}/patchList',
  '/cue/{cue_number}/playCount {number}',
  '/cue/{cue_number}/preserveAspectRatio {number}',
  '/cue/{cue_number}/quaternion {number number number number}',
  '/cue/{cue_number}/rate {number}',
  '/cue/{cue_number}/liveRate {number}',
  '/cue/{cue_number}/resetRotation',
  '/cue/{cue_number}/rotateX {number}',
  '/cue/{cue_number}/rotateY {number}',
  '/cue/{cue_number}/rotateZ {number}',
  '/cue/{cue_number}/liveRotation/Xaxis {number}',
  '/cue/{cue_number}/liveRotation/Yaxis {number}',
  '/cue/{cue_number}/liveRotation/Zaxis {number}',
  '/cue/{cue_number}/liveRotation/x {number}',
  '/cue/{cue_number}/liveRotation/y {number}',
  '/cue/{cue_number}/liveRotation/z {number}',
  '/cue/{cue_number}/scaleX {number}',
  '/cue/{cue_number}/liveScaleX {number}',
  '/cue/{cue_number}/scaleY {number}',
  '/cue/{cue_number}/liveScaleY {number}',
  '/cue/{cue_number}/scale {x} {y}',
  '/cue/{cue_number}/liveScale {x} {y}',
  '/cue/{cue_number}/setDefaultLevels',
  '/cue/{cue_number}/setSilentLevels',
  '/cue/{cue_number}sliceMarkers',
  '/cue/{cue_number}/sliceMarker {index}',
  '/cue/{cue_number}/sliceMarker/{index}',
  '/cue/{cue_number}/sliceMarker/{index}/time',
  '/cue/{cue_number}/sliceMarker/{index}/playCount',
  '/cue/{cue_number}/addSliceMarker {time} {play_count}',
  '/cue/{cue_number}/deleteSliceMarker {index}',
  '/cue/{cue_number}/deleteSliceMarker/{index}',
  '/cue/{cue_number}/deleteSliceMarkers',
  '/cue/{cue_number}/sliceMarker {index} {time} {play_count}',
  '/cue/{cue_number}/sliceMarker/{index} {time} {play_count}',
  '/cue/{cue_number}/sliceMarker/{index}/time {time}',
  '/cue/{cue_number}/sliceMarker/{index}/time/+ {delta}',
  '/cue/{cue_number}/sliceMarker/{index}/time/- {delta}',
  '/cue/{cue_number}/sliceMarkers/time/+ {delta}',
  '/cue/{cue_number}/sliceMarkers/time/- {delta}',
  '/cue/{cue_number}/sliceMarker/{index}/playCount {play_count}',
  '/cue/{cue_number}/sliceMarker/{index}/playCount/+ {delta}',
  '/cue/{cue_number}/sliceMarker/{index}/playCount/- {delta}',
  '/cue/{cue_number}/lastSlicePlayCount {play_count}',
  '/cue/{cue_number}/lastSliceInfiniteLoop {number}',
  '/cue/{cue_number}/sliderLevel {channel} {decibel}',
  '/cue/{cue_number}/sliderLevel/{channel} {decibel}',
  '/cue/{cue_number}/sliderLevels',
  '/cue/{cue_number}/startTime {number}',
  '/cue/{cue_number}/surfaceID {number}',
  '/cue/{cue_number}/surfaceList',
  '/cue/{cue_number}/surfaceName {string}',
  '/cue/{cue_number}/surfaceSize',
  '/cue/{cue_number}/translationX {number}',
  '/cue/{cue_number}/liveTranslationX {number}',
  '/cue/{cue_number}/translationY {number}',
  '/cue/{cue_number}/liveTranslationY {number}',
  '/cue/{cue_number}/translation {x} {y}',
  '/cue/{cue_number}/liveTranslation {x} {y}',
  '/cue/{cue_number}/cameraPatch',
  '/cue/{cue_number}/fixedWidth {number}',
  '/cue/{cue_number}/text {string}',
  '/cue/{cue_number}/liveText {string}',
  '/cue/{cue_number}/text/format {json_string}',
  '/cue/{cue_number}/text/format/alignment {alignment}',
  '/cue/{cue_number}/text/format/fontFamily',
  '/cue/{cue_number}/text/format/fontStyle',
  '/cue/{cue_number}/text/format/fontFamilyAndStyle {family} {style}',
  '/cue/{cue_number}/text/format/fontName {name}',
  '/cue/{cue_number}/text/format/fontSize {number}',
  '/cue/{cue_number}/text/format/lineSpacing {number}',
  '/cue/{cue_number}/text/format/color {red} {green} {blue} {alpha}',
  '/cue/{cue_number}/text/format/backgroundColor {red} {green} {blue} {alpha}',
  '/cue/{cue_number}/text/format/strikethroughColor {red} {green} {blue} {alpha}',
  '/cue/{cue_number}/text/format/underlineColor {red} {green} {blue} {alpha}',
  '/cue/{cue_number}/text/format/strikethroughStyle {style}',
  '/cue/{cue_number}/text/format/underlineStyle {style}',
  '/cue/{cue_number}/text/outputSize',
  '/cue/{cue_number}/liveText/outputSize',
  '/cue/{cue_number}/alwaysCollate {number}',
  '/cue/{cue_number}/collateAndStart',
  '/cue/{cue_number}/lightCommandText {string}',
  '/cue/{cue_number}/prune',
  '/cue/{cue_number}/pruneCommands',
  '/cue/{cue_number}/removeLightCommandsMatching {string}',
  '/cue/{cue_number}/replaceLightCommand {old_command} {new_command}',
  '/cue/{cue_number}/safeSort',
  '/cue/{cue_number}/safeSortCommands',
  '/cue/{cue_number}/setLight {string} {setting}',
  '/cue/{cue_number}/updateLightCommand {string} {number}',
  '/cue/{cue_number}/doOpacity {number}',
  '/cue/{cue_number}/doRate {number}',
  '/cue/{cue_number}/doRotation {number}',
  '/cue/{cue_number}/doScale {number}',
  '/cue/{cue_number}/doTranslation {number}',
  '/cue/{cue_number}/gang inChannel outChannel {gang}',
  '/cue/{cue_number}/gang/inChannel/outChannel {gang}',
  '/cue/{cue_number}/geoMode {number}',
  '/cue/{cue_number}/level inChannel outChannel {decibel}',
  '/cue/{cue_number}/level/inChannel/outChannel {decibel}',
  '/cue/{cue_number}/levels',
  '/cue/{cue_number}/mode {number}',
  '/cue/{cue_number}/opacity {number}',
  '/cue/{cue_number}/preserveAspectRatio {number}',
  '/cue/{cue_number}/quaternion {number number number number}',
  '/cue/{cue_number}/rate {number}',
  '/cue/{cue_number}/resetRotation',
  '/cue/{cue_number}/rotateX {number}',
  '/cue/{cue_number}/rotateY {number}',
  '/cue/{cue_number}/rotateZ {number}',
  '/cue/{cue_number}/rotation {number}',
  '/cue/{cue_number}/rotationType {number}',
  '/cue/{cue_number}/scaleX {number}',
  '/cue/{cue_number}/scaleY {number}',
  '/cue/{cue_number}/scale {x} {y}',
  '/cue/{cue_number}/setLevelsFromTarget',
  '/cue/{cue_number}/setSilentLevels',
  '/cue/{cue_number}/setGeometryFromTarget',
  '/cue/{cue_number}/sliderLevel {channel} {decibel}',
  '/cue/{cue_number}/sliderLevel/{channel} {decibel}',
  '/cue/{cue_number}/sliderLevels',
  '/cue/{cue_number}/stopTargetWhenDone {number}',
  '/cue/{cue_number}/translationX {number}',
  '/cue/{cue_number}/translationY {number}',
  '/cue/{cue_number}/translation {x} {y}',
  '/cue/{cue_number}/willFade {row} {column} {number}',
  '/cue/{cue_number}/customString {string}',
  '/cue/{cue_number}/messageType {number}',
  '/cue/{cue_number}/qlabCommand {number}',
  '/cue/{cue_number}/patch {number}',
  '/cue/{cue_number}/qlabCueNumber {string}',
  '/cue/{cue_number}/qlabCueParameters {string}',
  '/cue/{cue_number}/rawString {string}',
  '/cue/{cue_number}/udpString {string}',
  '/cue/{cue_number}/byte1 {number}',
  '/cue/{cue_number}/byte2 {number}',
  '/cue/{cue_number}/byteCombo {number}',
  '/cue/{cue_number}/channel {number}',
  '/cue/{cue_number}/command {number}',
  '/cue/{cue_number}/commandFormat {number}',
  '/cue/{cue_number}/controlNumber {number}',
  '/cue/{cue_number}/controlValue {number}',
  '/cue/{cue_number}/deviceID {number}',
  '/cue/{cue_number}/doFade {number}',
  '/cue/{cue_number}/endValue {number}',
  '/cue/{cue_number}/hours {number}',
  '/cue/{cue_number}/minutes {number}',
  '/cue/{cue_number}/seconds {number}',
  '/cue/{cue_number}/frames {number}',
  '/cue/{cue_number}/subframes {number}',
  '/cue/{cue_number}/macro {number}',
  '/cue/{cue_number}/messageType {number}',
  '/cue/{cue_number}/patch {number}',
  '/cue/{cue_number}/qList {string}',
  '/cue/{cue_number}/qNumber {string}',
  '/cue/{cue_number}/qPath {string}',
  '/cue/{cue_number}/rawString {string}',
  '/cue/{cue_number}/status {number}',
  '/cue/{cue_number}/timecodeFormat {number}',
  '/cue/{cue_number}/timecodeString {string}',
  '/cue/{cue_number}/patch {number}',
  '/cue/{cue_number}/rate {number}',
  '/cue/{cue_number}/startNextCueWhenSliceEnds {number}',
  '/cue/{cue_number}/stopTargetWhenSliceEnds {number}',
  '/cue/{cue_number}/compileSource',
  '/cue/{cue_number}/scriptSource',
]
