//Code to pull OSC API list from Figure 53 website:
// var cs = []; ps = document.getElementsByTagName('h4'); for (var i=0, len = ps.length; i<len; i++) {cs.push(ps[i].textContent);} JSON.stringify(cs).replace(/,/g, ',\n').replace(/\/workspace\/{id}\//g,'/').replace(/{cue_number}\//g, '{cue_identifier}/');
//Website is: https://qlab.app/docs/v4/scripting/osc-dictionary-v4/
export const qlabCommandList = [
  '/alwaysReply {number}',
  '/auditionWindow {number}',
  '/toggleAuditionWindow',
  '/fontNames',
  '/fontFamiliesAndStyles',
  '/liveFadePreview {number}',
  '/toggleLiveFadePreview',
  '/overrides/artNetEnabled {number}',
  '/overrides/toggleArtNet',
  '/overrides/midiInputEnabled {number}',
  '/overrides/toggleMidiInput',
  '/overrides/midiOutputEnabled {number}',
  '/overrides/toggleMidiOutput',
  '/overrides/mscInputEnabled {number}',
  '/overrides/toggleMscInput',
  '/overrides/mscOutputEnabled {number}',
  '/overrides/toggleMscOutput',
  '/overrides/sysexInputEnabled {number}',
  '/overrides/toggleSysexInput',
  '/overrides/sysexOutputEnabled {number}',
  '/overrides/toggleSysexOutput',
  '/overrides/oscInputEnabled {number}',
  '/overrides/toggleOscInput',
  '/overrides/oscOutputEnabled {number}',
  '/overrides/toggleOscOutput',
  '/overrides/timecodeInputEnabled {number}',
  '/overrides/toggleTimecodeInput',
  '/overrides/timecodeOutputEnabled {number}',
  '/overrides/toggleTimecodeOutput',
  '/overrideWindow {number}',
  '/toggleOverrideWindow',
  '/replyFormat {format_string}',
  '/timecodeWindow {number}',
  '/toggleTimecodeWindow',
  '/version',
  '/workingDirectory {path}',
  '/workspaces',
  '/basePath',
  '/connect {passcode_string}',
  '/disconnect',
  '/doubleGoWindowRemaining',
  '/cueLists',
  '/selectedCues',
  '/runningCues',
  '/runningOrPausedCues',
  '/cueLists/shallow',
  '/selectedCues/shallow',
  '/runningCues/shallow',
  '/runningOrPausedCues/shallow',
  '/cueLists/uniqueIDs',
  '/selectedCues/uniqueIDs',
  '/runningCues/uniqueIDs',
  '/runningOrPausedCues/uniqueIDs',
  '/cueLists/uniqueIDs/shallow',
  '/selectedCues/uniqueIDs/shallow',
  '/runningCues/uniqueIDs/shallow',
  '/runningOrPausedCues/uniqueIDs/shallow',
  '/dashboard/clear',
  '/dashboard/updateLatestCue',
  '/dashboard/updateOriginatingCues',
  '/dashboard/updateSelectedCues',
  '/dashboard/newCueWithAll',
  '/dashboard/newCueWithChanges',
  '/dashboard/recordAllToLatest',
  '/dashboard/recordAllToSelected',
  '/dashboard/revert',
  '/dashboard/redo',
  '/dashboard/mode {string}',
  '/dashboard/nextMode',
  '/dashboard/setLight {string} {setting} {time}',
  '/dashboard/undo',
  '/delete/{cue_number}',
  '/delete_id/{cue_id}',
  '/delete/active',
  '/delete/selected',
  '/fullScreen {number}',
  '/toggleFullScreen',
  '/go {cue_number}',
  '/go/{cue_number}',
  '/lightDashboard {number}',
  '/toggleLightDashboard',
  '/move/{cue_id} {new_index} {new_parent_cue_id}',
  '/new {cue_type}',
  '/panic',
  '/panicInTime {number}',
  '/pause',
  '/playhead/{cue_number}',
  '/playheadId/{cue_id}',
  '/playbackPosition/{cue_number}',
  '/playbackPositionId/{cue_id}',
  '/playhead/next',
  '/playbackPosition/next',
  '/playhead/previous',
  '/playbackPosition/previous',
  '/playhead/nextSequence',
  '/playbackPosition/nextSequence',
  '/playhead/previousSequence',
  '/playbackPosition/previousSequence',
  '/renumber {startNumber} {incrementNumber}',
  '/reset',
  '/resume',
  '/save',
  '/select/{cue_number}',
  '/select_id/{id}',
  '/select/next',
  '/select/previous',
  '/selectionIsPlayhead {number}',
  '/toggleSelectionIsPlayhead',
  '/showMode {number}',
  '/toggleEditShowMode',
  '/stop',
  '/hardStop',
  '/thump',
  '/undo',
  '/redo',
  '/updates {number}',
  '/settings/audio/maxVolume',
  '/settings/audio/minVolume',
  '/settings/audio/outputChannelNames',
  '/settings/mic/outputChannelNames',
  '/settings/general/minGoTime {number}',
  '/settings/video/surfaces',
  '/settings/video/surfaces/{surfaceID}',
  '/settings/video/surfaces/{surfaceID}/{screenIndex}/enableGrid {number}',
  '/settings/video/surfaces/{surfaceID}/{screenIndex}/enableGuides {number}',
  '/settings/video/surfaces/{surfaceID}/{screenIndex}/origin {location}',
  '/settings/video/surfaces/{surfaceID}/{screenIndex}/controlPoint {row_index} {column_index} {location}',
  '/settings/video/surfaces/{surfaceID}/{screenIndex}/resetControlPoints',
  '/cue/{cue_identifier}/actionElapsed',
  '/cue/{cue_identifier}/percentActionElapsed',
  '/cue/{cue_identifier}/allowsEditingDuration',
  '/cue/{cue_identifier}/armed {number}',
  '/cue/{cue_identifier}/autoLoad {number}',
  '/cue/{cue_identifier}/cartPosition',
  '/cue/{number}/children/shallow',
  '/cue/{number}/children/uniqueIDs',
  '/cue/{number}/children/uniqueIDs/shallow',
  '/cue/{cue_identifier}/colorName {string}',
  '/cue/{cue_identifier}/continueMode {number}',
  '/cue/{cue_identifier}/cueTargetId {string}',
  '/cue/{cue_identifier}/cueTargetNumber {string}',
  '/cue/{cue_identifier}/currentCueTarget',
  '/cue/{cue_identifier}/go',
  '/cue/{cue_identifier}/tempCueTargetNumber {string}',
  '/cue/{cue_identifier}/tempCueTargetId',
  '/cue/{cue_identifier}/currentDuration',
  '/cue/{cue_identifier}/tempDuration {number}',
  '/cue/{cue_identifier}/currentFileTime',
  '/cue/{cue_identifier}/defaultName',
  '/cue/{cue_identifier}/displayName',
  '/cue/{cue_identifier}/listName',
  '/cue/{cue_identifier}/duckLevel {number}',
  '/cue/{cue_identifier}/duckOthers {number}',
  '/cue/{cue_identifier}/duckTime {number}',
  '/cue/{cue_identifier}/duration {number}',
  '/cue/{cue_identifier}/fadeAndStopOthers {number}',
  '/cue/{cue_identifier}/fadeAndStopOthersTime {number}',
  '/cue/{cue_identifier}/fileTarget {string}',
  '/cue/{cue_identifier}/flagged {number}',
  '/cue/{cue_identifier}/hasCueTargets',
  '/cue/{cue_identifier}/hasFileTargets',
  '/cue/{cue_identifier}/isActionRunning',
  '/cue/{cue_identifier}/isBroken',
  '/cue/{cue_identifier}/isLoaded',
  '/cue/{cue_identifier}/isOverridden',
  '/cue/{cue_identifier}/isPanicking',
  '/cue/{cue_identifier}/isPaused',
  '/cue/{cue_identifier}/isRunning',
  '/cue/{cue_identifier}/isTailingOut',
  '/cue/{cue_identifier}/load',
  '/cue/{cue_identifier}/loadAt {number}',
  '/cue/{cue_identifier}/loadActionAt {number}',
  '/cue/{cue_identifier}/loadAndSetPlayhead',
  '/cue/{cue_identifier}/maxTimeInCueSequence',
  '/cue/{cue_identifier}/name {string}',
  '/cue/{cue_identifier}/notes {string}',
  '/cue/{cue_identifier}/number {string}',
  '/cue/{cue_identifier}/panic',
  '/cue/{cue_identifier}/panicInTime {number}',
  '/cue/{cue_identifier}/pause',
  '/cue/{cue_identifier}/hardPause',
  '/cue/{cue_identifier}/togglePause',
  '/cue/{cue_identifier}/parent',
  '/cue/{cue_identifier}/preview',
  '/cue/{cue_identifier}/preWait {number}',
  '/cue/{cue_identifier}/preWaitElapsed',
  '/cue/{cue_identifier}/percentPreWaitElapsed',
  '/cue/{cue_identifier}/postWait {number}',
  '/cue/{cue_identifier}/postWaitElapsed',
  '/cue/{cue_identifier}/percentPostWaitElapsed',
  '/cue/{cue_identifier}/resume',
  '/cue/{cue_identifier}/reset',
  '/cue/{cue_identifier}/secondTriggerAction {number}',
  '/cue/{cue_identifier}/secondTriggerOnRelease {number}',
  '/cue/{cue_identifier}/soloCueInTime {number}',
  '/cue/{cue_identifier}/start',
  '/cue/{cue_identifier}/startAndAutoloadNext',
  '/cue/{cue_identifier}/stop',
  '/cue/{cue_identifier}/hardStop',
  '/cue/{cue_identifier}/type',
  '/cue/{cue_identifier}/uniqueID',
  '/cue/{cue_identifier}/valuesForKeys {json_string}',
  '/cue/{cue_identifier}/valuesForKeysWithArguments {json_string}',
  '/cue/{cue_identifier}/cartColumns',
  '/cue/{cue_identifier}/cartRows',
  '/cue/{cue_identifier}/children',
  '/cue/{cue_identifier}/go',
  '/cue/{cue_identifier}/mode {number}',
  '/cue/{cue_identifier}/moveCartCue/{child} {row} {column}',
  '/cue/{cue_identifier}/playhead {string}',
  '/cue/{cue_identifier}/playbackPosition {string}',
  '/cue/{cue_identifier}/playheadId {string}',
  '/cue/{cue_identifier}/playbackPositionId {string}',
  '/cue/{cue_identifier}/doFade {number}',
  '/cue/{cue_identifier}/doPitchShift {number}',
  '/cue/{cue_identifier}/endTime {number}',
  '/cue/{cue_identifier}/gang {inChannel} {outChannel} {gang}',
  '/cue/{cue_identifier}/gang/{inChannel}/{outChannel} {gang}',
  '/cue/{cue_identifier}/infiniteLoop {number}',
  '/cue/{cue_identifier}/level {inChannel} {outChannel} {decibel}',
  '/cue/{cue_identifier}/level/{inChannel}/{outChannel} {decibel}',
  '/cue/{cue_identifier}/levels',
  '/cue/{cue_identifier}/liveAverageLevel/{outputChannel} {low} {high}',
  '/cue/{cue_identifier}/lockFadeToCue {number}',
  '/cue/{cue_identifier}/numChannelsIn',
  '/cue/{cue_identifier}/patch {number}',
  '/cue/{cue_identifier}/patchList',
  '/cue/{cue_identifier}/playCount {number}',
  '/cue/{cue_identifier}/rate {number}',
  '/cue/{cue_identifier}/liveRate {number}',
  '/cue/{cue_identifier}/setDefaultLevels',
  '/cue/{cue_identifier}/setSilentLevels',
  '/cue/{cue_identifier}/sliceMarkers',
  '/cue/{cue_identifier}/sliceMarker {index}',
  '/cue/{cue_identifier}/sliceMarker/{index}',
  '/cue/{cue_identifier}/sliceMarker/{index}/time',
  '/cue/{cue_identifier}/sliceMarker/{index}/playCount',
  '/cue/{cue_identifier}/addSliceMarker {time} {play_count}',
  '/cue/{cue_identifier}/deleteSliceMarker {index}',
  '/cue/{cue_identifier}/deleteSliceMarker/{index}',
  '/cue/{cue_identifier}/deleteSliceMarkers',
  '/cue/{cue_identifier}/sliceMarker {index} {time} {play_count}',
  '/cue/{cue_identifier}/sliceMarker/{index} {time} {play_count}',
  '/cue/{cue_identifier}/sliceMarker/{index}/time {time}',
  '/cue/{cue_identifier}/sliceMarker/{index}/time/+ {delta}',
  '/cue/{cue_identifier}/sliceMarker/{index}/time/- {delta}',
  '/cue/{cue_identifier}/sliceMarkers/time/+ {delta}',
  '/cue/{cue_identifier}/sliceMarkers/time/- {delta}',
  '/cue/{cue_identifier}/sliceMarker/{index}/playCount {play_count}',
  '/cue/{cue_identifier}/sliceMarker/{index}/playCount/+ {delta}',
  '/cue/{cue_identifier}/sliceMarker/{index}/playCount/- {delta}',
  '/cue/{cue_identifier}/lastSlicePlayCount {play_count}',
  '/cue/{cue_identifier}/lastSliceInfiniteLoop {number}',
  '/cue/{cue_identifier}/sliderLevel {channel} {decibel}',
  '/cue/{cue_identifier}/sliderLevel/{channel} {decibel}',
  '/cue/{cue_identifier}/sliderLevels',
  '/cue/{cue_identifier}/startTime {number}',
  '/cue/{cue_identifier}/channelOffset',
  '/cue/{cue_identifier}/channels {number}',
  '/cue/{cue_identifier}/setDefaultLevels',
  '/cue/{cue_identifier}/setSilentLevels',
  '/cue/{cue_identifier}/cueSize',
  '/cue/{cue_identifier}/doFade {number}',
  '/cue/{cue_identifier}/doPitchShift {number}',
  '/cue/{cue_identifier}/doEffect {number}',
  '/cue/{cue_identifier}/effectIndex {number}',
  '/cue/{cue_identifier}/effectSet {parameter} {value}',
  '/cue/{cue_identifier}/liveEffectSet {parameter} {value}',
  '/cue/{cue_identifier}/endTime {number}',
  '/cue/{cue_identifier}/fullScreen {number}',
  '/cue/{cue_identifier}/fullSurface {number}',
  '/cue/{cue_identifier}/gang {inChannel} {outChannel} {gang}',
  '/cue/{cue_identifier}/gang/{inChannel}/{outChannel} {gang}',
  '/cue/{cue_identifier}/holdLastFrame {number}',
  '/cue/{cue_identifier}/infiniteLoop {number}',
  '/cue/{cue_identifier}/layer {number}',
  '/cue/{cue_identifier}/level {inChannel} {outChannel} {decibel}',
  '/cue/{cue_identifier}/level/{inChannel}/{outChannel} {decibel}',
  '/cue/{cue_identifier}/levels',
  '/cue/{cue_identifier}/liveAverageLevel/{outputChannel} {low} {high}',
  '/cue/{cue_identifier}/lockFadeToCue {number}',
  '/cue/{cue_identifier}/numChannelsIn',
  '/cue/{cue_identifier}/opacity {number}',
  '/cue/{cue_identifier}/originX {number}',
  '/cue/{cue_identifier}/originY {number}',
  '/cue/{cue_identifier}/origin {x} {y}',
  '/cue/{cue_identifier}/patch {number}',
  '/cue/{cue_identifier}/patchList',
  '/cue/{cue_identifier}/playCount {number}',
  '/cue/{cue_identifier}/preserveAspectRatio {number}',
  '/cue/{cue_identifier}/quaternion {number number number number}',
  '/cue/{cue_identifier}/rate {number}',
  '/cue/{cue_identifier}/liveRate {number}',
  '/cue/{cue_identifier}/resetRotation',
  '/cue/{cue_identifier}/rotateX {number}',
  '/cue/{cue_identifier}/rotateY {number}',
  '/cue/{cue_identifier}/rotateZ {number}',
  '/cue/{cue_identifier}/liveRotation/Xaxis {number}',
  '/cue/{cue_identifier}/liveRotation/Yaxis {number}',
  '/cue/{cue_identifier}/liveRotation/Zaxis {number}',
  '/cue/{cue_identifier}/liveRotation/x {number}',
  '/cue/{cue_identifier}/liveRotation/y {number}',
  '/cue/{cue_identifier}/liveRotation/z {number}',
  '/cue/{cue_identifier}/scaleX {number}',
  '/cue/{cue_identifier}/liveScaleX {number}',
  '/cue/{cue_identifier}/scaleY {number}',
  '/cue/{cue_identifier}/liveScaleY {number}',
  '/cue/{cue_identifier}/scale {x} {y}',
  '/cue/{cue_identifier}/liveScale {x} {y}',
  '/cue/{cue_identifier}/setDefaultLevels',
  '/cue/{cue_identifier}/setSilentLevels',
  '/cue/{cue_number}sliceMarkers',
  '/cue/{cue_identifier}/sliceMarker {index}',
  '/cue/{cue_identifier}/sliceMarker/{index}',
  '/cue/{cue_identifier}/sliceMarker/{index}/time',
  '/cue/{cue_identifier}/sliceMarker/{index}/playCount',
  '/cue/{cue_identifier}/addSliceMarker {time} {play_count}',
  '/cue/{cue_identifier}/deleteSliceMarker {index}',
  '/cue/{cue_identifier}/deleteSliceMarker/{index}',
  '/cue/{cue_identifier}/deleteSliceMarkers',
  '/cue/{cue_identifier}/sliceMarker {index} {time} {play_count}',
  '/cue/{cue_identifier}/sliceMarker/{index} {time} {play_count}',
  '/cue/{cue_identifier}/sliceMarker/{index}/time {time}',
  '/cue/{cue_identifier}/sliceMarker/{index}/time/+ {delta}',
  '/cue/{cue_identifier}/sliceMarker/{index}/time/- {delta}',
  '/cue/{cue_identifier}/sliceMarkers/time/+ {delta}',
  '/cue/{cue_identifier}/sliceMarkers/time/- {delta}',
  '/cue/{cue_identifier}/sliceMarker/{index}/playCount {play_count}',
  '/cue/{cue_identifier}/sliceMarker/{index}/playCount/+ {delta}',
  '/cue/{cue_identifier}/sliceMarker/{index}/playCount/- {delta}',
  '/cue/{cue_identifier}/lastSlicePlayCount {play_count}',
  '/cue/{cue_identifier}/lastSliceInfiniteLoop {number}',
  '/cue/{cue_identifier}/sliderLevel {channel} {decibel}',
  '/cue/{cue_identifier}/sliderLevel/{channel} {decibel}',
  '/cue/{cue_identifier}/sliderLevels',
  '/cue/{cue_identifier}/startTime {number}',
  '/cue/{cue_identifier}/surfaceID {number}',
  '/cue/{cue_identifier}/surfaceList',
  '/cue/{cue_identifier}/surfaceName {string}',
  '/cue/{cue_identifier}/surfaceSize',
  '/cue/{cue_identifier}/translationX {number}',
  '/cue/{cue_identifier}/liveTranslationX {number}',
  '/cue/{cue_identifier}/translationY {number}',
  '/cue/{cue_identifier}/liveTranslationY {number}',
  '/cue/{cue_identifier}/translation {x} {y}',
  '/cue/{cue_identifier}/liveTranslation {x} {y}',
  '/cue/{cue_identifier}/cameraPatch',
  '/cue/{cue_identifier}/fixedWidth {number}',
  '/cue/{cue_identifier}/text {string}',
  '/cue/{cue_identifier}/liveText {string}',
  '/cue/{cue_identifier}/text/format {json_string}',
  '/cue/{cue_identifier}/text/format/alignment {alignment}',
  '/cue/{cue_identifier}/text/format/fontFamily',
  '/cue/{cue_identifier}/text/format/fontStyle',
  '/cue/{cue_identifier}/text/format/fontFamilyAndStyle {family} {style}',
  '/cue/{cue_identifier}/text/format/fontName {name}',
  '/cue/{cue_identifier}/text/format/fontSize {number}',
  '/cue/{cue_identifier}/text/format/lineSpacing {number}',
  '/cue/{cue_identifier}/text/format/color {red} {green} {blue} {alpha}',
  '/cue/{cue_identifier}/text/format/backgroundColor {red} {green} {blue} {alpha}',
  '/cue/{cue_identifier}/text/format/strikethroughColor {red} {green} {blue} {alpha}',
  '/cue/{cue_identifier}/text/format/underlineColor {red} {green} {blue} {alpha}',
  '/cue/{cue_identifier}/text/format/strikethroughStyle {style}',
  '/cue/{cue_identifier}/text/format/underlineStyle {style}',
  '/cue/{cue_identifier}/text/outputSize',
  '/cue/{cue_identifier}/liveText/outputSize',
  '/cue/{cue_identifier}/alwaysCollate {number}',
  '/cue/{cue_identifier}/collateAndStart',
  '/cue/{cue_identifier}/lightCommandText {string}',
  '/cue/{cue_identifier}/prune',
  '/cue/{cue_identifier}/pruneCommands',
  '/cue/{cue_identifier}/removeLightCommandsMatching {string}',
  '/cue/{cue_identifier}/replaceLightCommand {old_command} {new_command}',
  '/cue/{cue_identifier}/safeSort',
  '/cue/{cue_identifier}/safeSortCommands',
  '/cue/{cue_identifier}/setLight {string} {setting}',
  '/cue/{cue_identifier}/updateLightCommand {string} {number}',
  '/cue/{cue_identifier}/doOpacity {number}',
  '/cue/{cue_identifier}/doRate {number}',
  '/cue/{cue_identifier}/doRotation {number}',
  '/cue/{cue_identifier}/doScale {number}',
  '/cue/{cue_identifier}/doTranslation {number}',
  '/cue/{cue_identifier}/gang inChannel outChannel {gang}',
  '/cue/{cue_identifier}/gang/inChannel/outChannel {gang}',
  '/cue/{cue_identifier}/geoMode {number}',
  '/cue/{cue_identifier}/level inChannel outChannel {decibel}',
  '/cue/{cue_identifier}/level/inChannel/outChannel {decibel}',
  '/cue/{cue_identifier}/levels',
  '/cue/{cue_identifier}/mode {number}',
  '/cue/{cue_identifier}/opacity {number}',
  '/cue/{cue_identifier}/preserveAspectRatio {number}',
  '/cue/{cue_identifier}/quaternion {number number number number}',
  '/cue/{cue_identifier}/rate {number}',
  '/cue/{cue_identifier}/resetRotation',
  '/cue/{cue_identifier}/rotateX {number}',
  '/cue/{cue_identifier}/rotateY {number}',
  '/cue/{cue_identifier}/rotateZ {number}',
  '/cue/{cue_identifier}/rotation {number}',
  '/cue/{cue_identifier}/rotationType {number}',
  '/cue/{cue_identifier}/scaleX {number}',
  '/cue/{cue_identifier}/scaleY {number}',
  '/cue/{cue_identifier}/scale {x} {y}',
  '/cue/{cue_identifier}/setLevelsFromTarget',
  '/cue/{cue_identifier}/setSilentLevels',
  '/cue/{cue_identifier}/setGeometryFromTarget',
  '/cue/{cue_identifier}/sliderLevel {channel} {decibel}',
  '/cue/{cue_identifier}/sliderLevel/{channel} {decibel}',
  '/cue/{cue_identifier}/sliderLevels',
  '/cue/{cue_identifier}/stopTargetWhenDone {number}',
  '/cue/{cue_identifier}/translationX {number}',
  '/cue/{cue_identifier}/translationY {number}',
  '/cue/{cue_identifier}/translation {x} {y}',
  '/cue/{cue_identifier}/willFade {row} {column} {number}',
  '/cue/{cue_identifier}/customString {string}',
  '/cue/{cue_identifier}/messageType {number}',
  '/cue/{cue_identifier}/qlabCommand {number}',
  '/cue/{cue_identifier}/patch {number}',
  '/cue/{cue_identifier}/qlabCueNumber {string}',
  '/cue/{cue_identifier}/qlabCueParameters {string}',
  '/cue/{cue_identifier}/rawString {string}',
  '/cue/{cue_identifier}/udpString {string}',
  '/cue/{cue_identifier}/byte1 {number}',
  '/cue/{cue_identifier}/byte2 {number}',
  '/cue/{cue_identifier}/byteCombo {number}',
  '/cue/{cue_identifier}/channel {number}',
  '/cue/{cue_identifier}/command {number}',
  '/cue/{cue_identifier}/commandFormat {number}',
  '/cue/{cue_identifier}/controlNumber {number}',
  '/cue/{cue_identifier}/controlValue {number}',
  '/cue/{cue_identifier}/deviceID {number}',
  '/cue/{cue_identifier}/doFade {number}',
  '/cue/{cue_identifier}/endValue {number}',
  '/cue/{cue_identifier}/hours {number}',
  '/cue/{cue_identifier}/minutes {number}',
  '/cue/{cue_identifier}/seconds {number}',
  '/cue/{cue_identifier}/frames {number}',
  '/cue/{cue_identifier}/subframes {number}',
  '/cue/{cue_identifier}/macro {number}',
  '/cue/{cue_identifier}/messageType {number}',
  '/cue/{cue_identifier}/patch {number}',
  '/cue/{cue_identifier}/qList {string}',
  '/cue/{cue_identifier}/qNumber {string}',
  '/cue/{cue_identifier}/qPath {string}',
  '/cue/{cue_identifier}/rawString {string}',
  '/cue/{cue_identifier}/status {number}',
  '/cue/{cue_identifier}/timecodeFormat {number}',
  '/cue/{cue_identifier}/timecodeString {string}',
  '/cue/{cue_identifier}/patch {number}',
  '/cue/{cue_identifier}/rate {number}',
  '/cue/{cue_identifier}/startNextCueWhenSliceEnds {number}',
  '/cue/{cue_identifier}/stopTargetWhenSliceEnds {number}',
  '/cue/{cue_identifier}/compileSource',
  '/cue/{cue_identifier}/scriptSource',
]
